// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OpenCMS.Domain.Entities
{
    public partial class Transactions:BaseEntity<int>
    {
        public Transactions()
        {
            SalesItems = new HashSet<TransactionItems>();
        }

        public int Id { get; set; }
        public int? CardFileId { get; set; }
        public decimal? TotalAmount { get; set; }
        public decimal? Discount { get; set; }
        public int? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public virtual CardFiles CardFile { get; set; }
        public virtual ICollection<TransactionItems> SalesItems { get; set; }
        public int TransactionType { get; set; }
    }
}