// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OpenCMS.Domain.Entities
{
    public partial class TransactionItems:BaseEntity<int>
    {
        public int Id { get; set; }
        public int? TransactionId { get; set; }
        public int? CatalogId { get; set; }
        public decimal? Quantity { get; set; }
        public int? DiscountId { get; set; }
        public decimal? SubTotal { get; set; }
        public  virtual Catalogs Catalogs { get; set; }
        public virtual Transactions Sales { get; set; }
    }
}